spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    #    url: jdbc:postgresql://192.168.1.172:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#'#spring':
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#  datasource:
#    hikari:
#      auto-commit: true
